### ISSUE TITLE
API Limit not working?

### ISSUE THREAD

**Issue by sebo83910** [peeter123/digikey-api#20]
Hello,

I tried the example given [here](https://github.com/peeter123/digikey-api#api-limits).

$ python ./pydigikey.py
TTraceback (most recent call last):
  File "./pydigikey.py", line 48, in <module>
    result = digikey.keyword_search(body=search_request, api_limits=api_limit)
  File "/usr/local/lib/python3.8/site-packages/digikey/v3/api.py", line 77, in keyword_search
    return client.call_api_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/digikey/v3/api.py", line 64, in call_api_function
    api_response = func(*args, self.authorization, self.x_digikey_client_id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/digikey/v3/productinformation/api/part_search_api.py", line 240, in keyword_search_with_http_info
    raise TypeError(
TypeError: Got an unexpected keyword argument 'api_limits' to method keyword_search

**Comment by sebo83910** [comment]
uninstalled digik-api and tried this: [here](https://github.com/peeter123/digikey-api/issues/10#issuecomment-749590790)
it worked.
