### ISSUE TITLE
Getting a KeyError

### ISSUE THREAD

**Issue by TurAslan** [peeter123/digikey-api#4]
I've had some issues with this particular item. Other components work fine but this one: 1690-RASPBERRYPI4B/4GB-ND (digikey part number). This is what I get when trying to run digikey.part function.

> digikey.part('1690-RASPBERRYPI4B/4GB-ND')
2020-03-20 10:52:06,656 - digikey.oauth2 - DEBUG: Saved token to: D:\Work\NTS_repos\DigikeyTranslator\token_storage.json
2020-03-20 10:52:07,580 - digikey.decorators - ERROR: Wrapped error: 'x-ratelimit-limit'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\decorators.py", line 25, in inner
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\decorators.py", line 62, in inner
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\client.py", line 90, in _request_get
    rate_limit = re.split('[,;]+', response.headers['x-ratelimit-limit'])[0]
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-limit'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\api.py", line 62, in part
    include_for_use_with=include_for_use_with,
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\client.py", line 168, in part
    return self._request_get('/Search/v3/Products/{}'.format(partnr), data=params)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\digikey\decorators.py", line 34, in inner
    raise exc_type(message) from exc
digikey.exceptions.DigikeyError: KeyError

I've managed to get a proper response from digikey in their developer portal demo (https://developer.digikey.com/products/product-information/partsearch/productdetails?prod=true), so I don't think it's on digikey. I've tried putting time delays and running separately but no success.

**Comment by peeter123** [comment]
Looks like the API sometimes does not return the rate-limit information
