### ISSUE TITLE
OAuth trouble

### ISSUE THREAD

**Issue by coratron** [peeter123/digikey-api#44]
Hi, 

Something is not quite working for me. The browser pops up with the "accept security risk and continue". I click on the button, the code gets displayed on the browser but that's when the problems start.

It prints up to the following line on the terminal, and when I close the browser the rest of errors get printed. Not sure if that's of any help. 
```
IndexError: list index out of range
```

```

2023-07-19 23:56:58,269 - digikey.oauth.oauth2 -    DEBUG: Using API V3
2023-07-19 23:56:58,269 - digikey.oauth.oauth2 -  WARNING: Oauth2 token storage does not exist or malformed, creating new.
2023-07-19 23:56:58,269 - digikey.oauth.oauth2 -    DEBUG: AUTH - Authenticating with endpoint https://api.digikey.com/v1/oauth2/authorize using ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx...
2023-07-19 23:56:58,269 - digikey.oauth.oauth2 -    DEBUG: AUTH - Redirect URL: https://localhost:8139/digikey_callback
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/gabriel/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriel/Documents/Repositories/inventree-getparts/webcam_example.py", line 16, in <module>
    api = getparts.API(None, debug=False, use_api=True)
  File "/home/gabriel/Documents/Repositories/inventree-getparts/getparts.py", line 68, in __init__
    self.DigikeyAPI = DigikeyAPI(use_api=use_api)
  File "/home/gabriel/Documents/Repositories/inventree-getparts/digikey_API.py", line 8, in __init__
    digikey.product_details()
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/digikey/v3/api.py", line 83, in product_details
    client = ProductApiWrapper('product_details_with_http_info')
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/digikey/v3/api.py", line 39, in __init__
    self._digikeyApiToken = digikey.oauth.oauth2.TokenHandler(version=3, sandbox=self.sandbox).get_access_token()
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/digikey/oauth/oauth2.py", line 277, in get_access_token
    token_json = self.__exchange_for_token(httpd.auth_code)
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/digikey/oauth/oauth2.py", line 164, in __exchange_for_token
    headers = {'user-agent': f'{UserAgent().firefox}',
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 187, in load
    ret = json.loads(get(
  File "/home/gabriel/.pyenv/versions/apps39a/lib/python3.9/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by coratron** [comment]
Nevermind - it is an issue with the fake-useragent module. There was a typo in the my version. Solution can be found here:
[https://stackoverflow.com/questions/68772211/fake-useragent-module-not-connecting-properly-indexerror-list-index-out-of-ra](url)
A version that worked for me is the one mention there:
```
pip3 install fake-useragent==0.1.13
```
